Really chemistry only okay?
OpenVanilla/McBopomofo pull request #442
Opened 2024-02-29 23:02 UTC by olivertzeng

some other notable stuff
* unarguable chewing fixes from 簡編本
* removed duplicates with `perl -i -lne 'print unless $seen{$_}++' filename`

2024-02-29 23:09 UTC, olivertzeng commented
really sorry about the last pr
chemist = 只有化學的東西

2024-03-01 03:51 UTC, lukhnos requested changes
謝謝。我針對 PR 內容留了評論。

我對 PR 形式上（也就是 PR / commit title 以及 PR 描述）有兩條意見：

1. 請問標題 "Really chemistry only okay?" 的用意是？我不太明白在 PR / commit title 中出現疑問句，要傳達的意義是什麼。
2. 請問 PR description 中，"unarguable chewing fixes from 簡編本" 的意思是什麼呢？我讀起來，這是三件不一樣的事。什麼是 "unarguable"? 我以為發送 PR 本身就已經是在提出意見，"to make an argument (that the developers should accept the proposed change)"，也許是我不了解你的用意？此外，你提到酷音輸入法，是否你 PR 的修訂，是起源自酷音專案中的 PR 或討論？如果是這樣，是否能提供相關連結？如果「簡編本」指的是《國語辭典簡編本》，請問是否能擇要引用來源？

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFBase.txt
> +殯 ㄅㄧㄣ bin 1up big5
這不是化學相關字。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFBase.txt
> +羥 ㄎㄥ keng d/ big5
先前 review 忘了提，如果要在 BPMFBase.txt 增加新字，請增加在既有同音字之後。以這個例子來說，這必須加在「鍞」之後。原因請參見 [wiki 詞庫開發說明](https://github.com/openvanilla/McBopomofo/wiki/詞庫開發說明)對於修改這個檔案對傳統注音用戶的影響。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFBase.txt
> +酐 ㄍㄢ gan e0 big5
請加在其他ㄎㄢ同音字的末尾，以這個例子來說，加在「苷」之後。其他在這個中 PR 對於  `BPMFBase.txt` 的修訂亦同，以下不再重覆 review comment。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFBase.txt
> +燥 ㄙㄠˋ sao4 nl4 big5
不是化學用字。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFBase.txt
> +佛 ㄈㄨˊ fu2 zj6 big5
不是化學用字。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> -埤頭鄉 ㄆㄧˊ ㄊㄡˊ ㄒㄧㄤ
不是化學相關詞。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> +布侖斯惕洛瑞理論 ㄅㄨˋ ㄌㄨㄣˊ ㄙ ㄊㄧˋ ㄌㄨㄛˋ ㄖㄨㄟˋ  ㄌㄧˇ ㄌㄨㄣˋ
小麥只接受最多六字詞，超過的定義都沒有作用，下同。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> +布洛 ㄅㄨˋ ㄌㄨㄛˋ
這跟「部落」同音，要用的人應該考慮自行加入用戶自訂詞。

此外「理論」「學說」「酸鹼」等詞不需要再加入這類定義中。這些都是相當高頻率的中文二字詞。

而且說來，正確的寫法，應該是「布-洛酸鹼學說」？

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> +電子點式 ㄉㄧㄢˋ ㄗ˙ ㄉㄧㄢˇ ㄕˋ
在我們決定是否大幅收納輕聲「子」念法前，我們不考慮加入其他讀音。以下其他有「子」的讀音定意義亦同，不再重複 review comment。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> +路易士電子點式 ㄌㄨˋ ㄧˋ ㄕˋ ㄉㄧㄢˋ ㄗ˙ ㄉㄧㄢˇ ㄕˋ
「路易士」跟「路易斯」都已經是小麥已有詞彙。 小麥只接受至多六字詞。下同。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> +飛米 ㄈㄟ ㄇㄧˇ
我以為台灣一般作「費米」？請問有常見台灣文獻使用「飛米」的例子嗎？

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/BPMFPunctuations.txt
> -? _punctuation_list 0.0
非化學相關修訂。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/Symbols.txt
> -🥜 ㄏㄨㄚ-ㄕㄥ -8
非化學相關修訂。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/heterophony2.list
> -吐 ㄊㄨˇ
非化學相關修訂。

2024-03-01 03:51 UTC, lukhnos commented on Source/Data/phrase.occ
> -呆呆地 0
非化學相關修訂。

2024-03-01 03:59 UTC, olivertzeng commented
> 謝謝。我針對 PR 內容留了評論。
> 
> 
> 
> 我對 PR 形式上（也就是 PR / commit title 以及 PR 描述）有兩條意見：
> 
> 
> 
> 1. 請問標題 "Really chemistry only okay?" 的用意是？我不太明白在 PR / commit title 中出現疑問句，要傳達的意義是什麼。
> 
> 2. 請問 PR description 中，"unarguable chewing fixes from 簡編本" 的意思是什麼呢？我讀起來，這是三件不一樣的事。什麼是 "unarguable"? 我以為發送 PR 本身就已經是在提出意見，"to make an argument (that the developers should accept the proposed change)"，也許是我不了解你的用意？此外，你提到酷音輸入法，是否你 PR 的修訂，是起源自酷音專案中的 PR 或討論？如果是這樣，是否能提供相關連結？如果「簡編本」指的是《國語辭典簡編本》，請問是否能擇要引用來源？

1. 已修改
2. 修改的讀音皆出自《國語辭典簡編本》所以不是像電子ㄗ˙的個人preference 修改

2024-03-01 12:12 UTC, olivertzeng commented
> 謝謝。我針對 PR 內容留了評論。
> 
> 
> 
> 我對 PR 形式上（也就是 PR / commit title 以及 PR 描述）有兩條意見：
> 
> 
> 
> 1. 請問標題 "Really chemistry only okay?" 的用意是？我不太明白在 PR / commit title 中出現疑問句，要傳達的意義是什麼。
> 
> 2. 請問 PR description 中，"unarguable chewing fixes from 簡編本" 的意思是什麼呢？我讀起來，這是三件不一樣的事。什麼是 "unarguable"? 我以為發送 PR 本身就已經是在提出意見，"to make an argument (that the developers should accept the proposed change)"，也許是我不了解你的用意？此外，你提到酷音輸入法，是否你 PR 的修訂，是起源自酷音專案中的 PR 或討論？如果是這樣，是否能提供相關連結？如果「簡編本」指的是《國語辭典簡編本》，請問是否能擇要引用來源？

我有提到酷注音？
要是有那可能是我打錯字或是我常常commit message 都會亂打

2024-03-01 12:13 UTC, olivertzeng commented on Source/Data/BPMFBase.txt
> +殯 ㄅㄧㄣ bin 1up big5
對但這是注音修正
也就是說本來殯
就是念ㄅㄧㄣ

2024-03-01 12:13 UTC, olivertzeng commented on Source/Data/BPMFBase.txt
> +殯 ㄅㄧㄣ bin 1up big5
是否刪除

2024-03-01 12:13 UTC, olivertzeng commented on Source/Data/BPMFBase.txt
> +羥 ㄎㄥ keng d/ big5
Ok

2024-03-01 12:14 UTC, olivertzeng commented on Source/Data/BPMFBase.txt
> +酐 ㄍㄢ gan e0 big5
Ok

2024-03-01 12:14 UTC, olivertzeng commented on Source/Data/BPMFBase.txt
> +燥 ㄙㄠˋ sao4 nl4 big5
一樣是為修正注音
是否刪除？

2024-03-01 12:14 UTC, olivertzeng commented on Source/Data/BPMFBase.txt
> +佛 ㄈㄨˊ fu2 zj6 big5
一樣是為修正注音
是否刪除？

2024-03-01 12:15 UTC, olivertzeng commented on Source/Data/BPMFMappings.txt
> -埤頭鄉 ㄆㄧˊ ㄊㄡˊ ㄒㄧㄤ
那是duplicate 是perl 自動判斷的
有相同的字詞出現時會自動刪除多餘的

2024-03-01 12:15 UTC, olivertzeng commented on Source/Data/BPMFMappings.txt
> +布侖斯惕洛瑞理論 ㄅㄨˋ ㄌㄨㄣˊ ㄙ ㄊㄧˋ ㄌㄨㄛˋ ㄖㄨㄟˋ  ㄌㄧˇ ㄌㄨㄣˋ
Ok

2024-03-01 12:17 UTC, olivertzeng commented on Source/Data/BPMFMappings.txt
> +布洛 ㄅㄨˋ ㄌㄨㄛˋ
抱歉我會刪除

2024-03-01 12:17 UTC, olivertzeng commented on Source/Data/BPMFMappings.txt
> +電子點式 ㄉㄧㄢˋ ㄗ˙ ㄉㄧㄢˇ ㄕˋ
Ok我也會刪除

2024-03-01 12:17 UTC, olivertzeng commented on Source/Data/BPMFMappings.txt
> +路易士電子點式 ㄌㄨˋ ㄧˋ ㄕˋ ㄉㄧㄢˋ ㄗ˙ ㄉㄧㄢˇ ㄕˋ
Ok

2024-03-01 12:18 UTC, olivertzeng commented on Source/Data/BPMFMappings.txt
> +飛米 ㄈㄟ ㄇㄧˇ
有![image](https://github.com/openvanilla/McBopomofo/assets/86348833/4e563f4b-f4c6-4c2c-9090-923b78812666)

2024-03-01 12:18 UTC, olivertzeng commented on Source/Data/BPMFPunctuations.txt
> -? _punctuation_list 0.0
是多餘字詞duplicate 由perl 自動判斷

2024-03-01 12:19 UTC, olivertzeng commented on Source/Data/Symbols.txt
> -🥜 ㄏㄨㄚ-ㄕㄥ -8
同上為dup

2024-03-01 12:19 UTC, olivertzeng commented on Source/Data/heterophony2.list
> -吐 ㄊㄨˇ
Duplicate

2024-03-01 12:19 UTC, olivertzeng commented on Source/Data/phrase.occ
> -呆呆地 0
Duplicate

2024-03-01 12:19 UTC, olivertzeng commented
我已回覆所有評論
等等會修改
@lukhnos

2024-03-01 14:11 UTC, olivertzeng commented
我已經完成幾乎所有更改以及不太確定是否 revert commit 的字詞
* 飛米
* perl 所判定的 duplicate
* 錯誤的讀音（正確讀音來源：簡編本）

2024-03-01 18:26 UTC, lukhnos requested changes
謝謝。以下三點意見。

首先，這個 PR 離完成還缺一步：新增詞條也需要在 `phrase.occ` 登錄。請參考[詞庫開發說明](https://github.com/openvanilla/McBopomofo/wiki/詞庫開發說明#新增詞彙)。出現次數填 0 就可以。

再來，你有在自己機器上試過這個 PR 製出的詞庫檔嗎？雖然 McBopomofo 是 macOS 專案，但是 `Source/Data` 裡的 `Makefile` 可以在 Linux 平台上執行。你可以打 `make` 後，把製出的 `data.txt` 拿來跟 `/usr/share/fcitx5/data/mcbopomofo-data.txt` 作比較，就知道自己修正以及新增的詞，到底有沒有編進最後的成果裡──這是另一個我會建議詞庫修改 PR 範圍要小的原因：大 PR 製出的 `data.txt` 很難查核結果是否正確。比對完後，你可以拿新檔蓋寫舊檔，重新啟動 fcitx5，就可以使用自己 PR 修改過的詞庫。

最後，目前你是用新增 commit 的方式回應 PR review comments（這是 ok 的），但第一個 commit 的 commit message 仍是 `Really chemistry only okay?` 因此，請將這幾個 commit 給 squash 成一個，趁此機會將 commit message 改為符合這個 PR 用意的敘述。

回應你的問題：

> > 我對 PR 形式上（也就是 PR / commit title 以及 PR 描述）有兩條意見：
> > 2. 請問 PR description 中，"unarguable chewing fixes from 簡編本" 的意思是什麼呢？[…]此外，你提到酷音輸入法，是否你 PR 的修訂，是起源自酷音專案中的 PR 或討論？[…]
> 我有提到酷注音？ 要是有那可能是我打錯字或是我常常commit message 都會亂打

如附圖，你的英文敘述是 "unarguable **chewing** fixes"，此處 chewing 如果指的不是新酷音輸入法專案，請問意思是？

![image](https://github.com/openvanilla/McBopomofo/assets/25210/a605502e-f63a-4508-9139-ac363489471f)

2024-03-01 18:26 UTC, lukhnos commented on Source/Data/BPMFBase.txt
> +殯 ㄅㄧㄣ bin 1up big5
這是有意義的修正，但是超出這個 PR 的範圍。我的建議是拆開來，放在另一個 branch 來製發 PR。

2024-03-01 18:26 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> -埤頭鄉 ㄆㄧˊ ㄊㄡˊ ㄒㄧㄤ
我覺得 de-dup 應該獨立製作一份 PR（請跟「殯」讀音修正分開處理）。有兩個好處：

1. 這樣的 PR 容易 review，主題單一
2. 日後我們可以照 PR 建議 rerun 你的 de-dup 手續，或者供日後維護者參考，變成[詞庫開發](https://github.com/openvanilla/McBopomofo/wiki/詞庫開發說明)的範例 PR

2024-03-01 18:26 UTC, lukhnos commented on Source/Data/BPMFPunctuations.txt
> -? _punctuation_list 0.0
同上述，請跟「埤頭鄉」一併處理。

2024-03-01 18:26 UTC, lukhnos commented on Source/Data/Symbols.txt
> -🥜 ㄏㄨㄚ-ㄕㄥ -8
見上述 de-dup 相關意見，以下不再重複。

2024-03-01 18:26 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> +飛米 ㄈㄟ ㄇㄧˇ
這不是「常見台灣文獻」的意思，我需要的是第一手來源資料（「[可靠來源](https://zh.wikipedia.org/zh-tw/Wikipedia:非原創研究#可靠来源)」，說明台灣有人用「飛米」一詞，或是官方規定這個長度單位要寫作飛米。。

[這則 Wikipedia 條目](https://zh.wikipedia.org/zh-tw/國際單位制詞頭) 引用了經濟部《[法定度量衡單位及其所用之倍數、分數之名稱、定義及代號](https://www.bsmi.gov.tw/wSite/public/Attachment/f1602827087740.pdf)》，第 12 頁列出 femto 的前綴確實是「飛」。

TIL.

2024-03-02 05:05 UTC, olivertzeng commented
> > > 2. 請問 PR description 中，"unarguable chewing fixes from 簡編本" 的意思是什麼呢？[…]此外，你提到酷音輸入法，是否你 PR 的修訂，是起源自酷音專案中的 PR 或討論？[…]
> > > 我有提到酷注音？ 要是有那可能是我打錯字或是我常常commit message 都會亂打
> 
> 如附圖，你的英文敘述是 "unarguable **chewing** fixes"，此處 chewing 如果指的不是新酷音輸入法專案，請問意思是？
> 
> ![image](https://private-user-images.githubusercontent.com/25210/309353344-a605502e-f63a-4508-9139-ac363489471f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTU5NTIsIm5iZiI6MTcwOTM1NTY1MiwicGF0aCI6Ii8yNTIxMC8zMDkzNTMzNDQtYTYwNTUwMmUtZjYzYS00NTA4LTkxMzktYWMzNjM0ODk0NzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA1MDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYTNiNjJjNTRjZjVjNzkxYzlkNGU1MDIyMmQwODE2N2I1ZTg2MDA3YWZkYTc1MTE0NmY3OTJjMjEwMTg5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cuUw6lu9hD5Wvue7ONWoZaxGMFlin0gZeqU-QBHZskg)

抱歉我以為 *chewing* 是指**注音**不是**酷注音** aka 我以為 chewing == bpmf
我會試試看在我的local machine 上使用詞
也會補上 phrase.occ

> 最後，目前你是用新增 commit 的方式回應 PR review comments（這是 ok 的），但第一個 commit 的 commit message 仍是 `Really chemistry only okay?` 因此，請將這幾個 commit 給 squash 成一個，趁此機會將 commit message 改為符合這個 PR 用意的敘述。
我不會弄ㄟ 但我會去查查看怎麼用

2024-03-02 05:30 UTC, olivertzeng commented on Source/Data/BPMFMappings.txt
> +飛米 ㄈㄟ ㄇㄧˇ
已刪除
但我個人認為這只是跟電ㄗ˙一樣是personal preferences

2024-03-02 05:32 UTC, olivertzeng commented
已完成修改（除了squash commit以外）
@lukhnos

2024-03-02 06:03 UTC, olivertzeng commented
close

2024-03-02 06:03 UTC, closed without merging

2024-03-02 06:07 UTC, olivertzeng commented
https://github.com/openvanilla/McBopomofo/pull/443

2024-03-02 12:42 UTC, lukhnos commented
> close

其實可以透過 `git rebase -i` + `git push -f` 等指令來達成 squash commits、修訂 commit 內容的目的。既然你開了 #444，這一點僅作為日後回應 PR review comments 的建議，供你參考。

2024-03-02 12:53 UTC, olivertzeng commented
Ok Sent from Proton Mail for iOS 
於 週六, 3月 2, 2024 時間 20:42, Lukhnos Liu ***@***.***&gt; 寫道：  
close

其實可以透過 git rebase -i + git push -f 等指令來達成 squash commits、修訂 commit 內容的目的。既然你開了 #444，這一點僅作為日後回應 PR review comments 的建議，供你參考。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;