Fix incorrect phonetics 著 words
OpenVanilla/McBopomofo pull request #484
Opened 2024-05-22 03:00 UTC by xatier

There's no ㄓㄨˇ

Ref:

https://dict.revised.moe.edu.tw/search.jsp?md=1&word=%E8%91%97#searchL https://www.moedict.tw/%E4%B8%89%E5%8D%81%E5%85%AD%E8%91%97%EF%BC%8C%E8%B5%B0%E7%82%BA%E4%B8%8A%E8%91%97 https://www.moedict.tw/%E8%91%97%E6%89%8B
https://www.moedict.tw/%E6%8B%99%E8%91%97
https://www.moedict.tw/%E6%B2%89%E8%91%97
https://www.moedict.tw/%E8%91%97%E5%AF%A6
https://www.moedict.tw/%E8%91%97%E6%80%A5
https://www.moedict.tw/%E9%A1%AF%E8%91%97

2024-05-22 03:00 UTC, xatier commented
@lukhnos please take a look :pray:

2024-05-22 13:48 UTC, lukhnos requested changes

2024-05-22 13:48 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> -沈著 ㄔㄣˊ ㄓㄨㄛˊ
This seems to be the cause of the build failure: https://github.com/openvanilla/McBopomofo/actions/runs/9184669125/job/25257375803?pr=484

```
bin/cook.py PhraseFreq.txt BPMFMappings.txt BPMFBase.txt BPMFPunctuations.txt Symbols.txt Macros.txt data.txt
Error:  沈著 key mismatches.
```

2024-05-22 15:06 UTC, xatier commented on Source/Data/BPMFMappings.txt
> -沈著 ㄔㄣˊ ㄓㄨㄛˊ
Oops, thanks for pointing this out. I've removed that from `phrase.occ`. 

`沈著` is incorrect, it should be `沉著`

https://www.moedict.tw/%E6%B2%89%E8%91%97

2024-05-23 18:27 UTC, lukhnos requested changes
Please roll back the changes to `BPMFBase.txt` and `phrase.occ` as well as the deletion of the entry for `沈著`, for the reason commented. Otherwise this LGTM. Thanks!

2024-05-23 18:27 UTC, lukhnos commented on Source/Data/BPMFBase.txt
> -著 ㄓㄨˇ zhu3 5j3 big5
不好意思現在才想到：這個是原有 xcin bpmf.cin 收錄的讀音。雖然是錯的，但基於歷史因素，我們應該保留。

2024-05-23 18:36 UTC, lukhnos requested changes

2024-05-23 18:36 UTC, lukhnos commented on Source/Data/BPMFMappings.txt
> -沈著 ㄔㄣˊ ㄓㄨㄛˊ
這個應該保留，因為詞庫收了同類詞：沉船/沈船、沉默/沈默等等。

2024-05-23 18:36 UTC, lukhnos commented on Source/Data/phrase.occ
> -沈著 12
我認為這個應該 revert，請參見我在 Source/Data/BPMFMappings.txt 留的意見。

2024-05-23 18:37 UTC, xatier commented on Source/Data/BPMFMappings.txt
> -沈著 ㄔㄣˊ ㄓㄨㄛˊ
sure, let me revert this.

2024-05-23 18:44 UTC, xatier commented
@lukhnos thanks for the feedbacks, I've reverted those deletions and squashed the commits so we have cleaner commit history.

2024-05-23 18:52 UTC, lukhnos approved these changes
Thank you!

2024-05-23 18:53 UTC, merged

2024-05-24 00:17 UTC, tianjianjiang commented on Source/Data/BPMFMappings.txt
> -沈著 ㄔㄣˊ ㄓㄨㄛˊ
@xatier @lukhnos FYI: 而且「沉」一向很有爭議。以某些古籍和主管機關的看法來說，「沉」才是異體字。

2024-05-24 00:26 UTC, xatier commented on Source/Data/BPMFMappings.txt
> -沈著 ㄔㄣˊ ㄓㄨㄛˊ
Interesting, my understanding is that `沈` is used mostly as a surname, and `沉` is used for `sunk`.

2024-05-24 00:28 UTC, xatier commented on Source/Data/BPMFMappings.txt
> -沈著 ㄔㄣˊ ㄓㄨㄛˊ
https://dict.variants.moe.edu.tw/dictView.jsp?ID=23377