Add missing character 蔴
OpenVanilla/McBopomofo pull request #508
Opened 2024-07-07 13:24 UTC by xatier

Ref:

https://www.moedict.tw/%E8%94%B4
https://dict.variants.moe.edu.tw/dictView.jsp?ID=53079&q=1 https://www.wikiwand.com/zh-tw/%E9%BA%BB%E8%8A%9B

2024-07-08 16:37 UTC, tianjianjiang requested changes

2024-07-08 16:37 UTC, tianjianjiang commented on Source/Data/BPMFMappings.txt
> +麻芛 ㄇㄚˊ ㄧˋ
```suggestion
```
就我所知「芛」在 Mandarin 裡沒有「ㄧˋ」的音。

2024-07-08 16:59 UTC, xatier commented on Source/Data/BPMFMappings.txt
> +麻芛 ㄇㄚˊ ㄧˋ
There's none, but I'd like to offer this so we can type this character with the commonly used pronunciation `ㄇㄚˊ ㄧˋ`

2024-07-08 17:57 UTC, ChiahongHong commented on Source/Data/BPMFMappings.txt
> +麻芛 ㄇㄚˊ ㄧˋ
In Taichung and northern Changhua (where I'm from), people probably won't pronounce it as `ㄇㄚˊ ㄨㄟˇ`, even though it's the correct pronunciation. We would likely pronounce it as `ㄧˋ`, whether we see `芛` or `薏`.

It makes sense to me 🤣

2024-07-08 18:11 UTC, ChiahongHong commented on Source/Data/phrase.occ
> +麻芛 0
duplicate, we should keep only one

2024-07-09 00:20 UTC, xatier commented on Source/Data/phrase.occ
> +麻芛 0
nice catch, thanks!

2024-07-09 08:30 UTC, tianjianjiang commented on Source/Data/BPMFMappings.txt
> +麻芛 ㄇㄚˊ ㄧˋ
這些考量我其實都沒意見，大致上只是看要不要建立某種收錄不在字典中的俗音的原則。
印象中這類型的字詞以前好像有過。 @lukhnos @mjhsieh @zonble 有印象嗎？

附帶一提，我猜這個發音來自當地的台語，不過有趣的是，雖然日文漢字也有相近的發音，但漢語中古音似乎沒有。可能也因為沒有中古音，教育部才會推薦那個音的台語漢字為「穎」。

2024-07-10 00:12 UTC, xatier commented on Source/Data/BPMFMappings.txt
> +麻芛 ㄇㄚˊ ㄧˋ
芛 means 嫩芽. 穎 has the same meaning, e.g., 發穎 huat-ínn means 發芽.

2024-07-10 00:40 UTC, xatier commented
Rebase on top of master.

2024-07-10 00:48 UTC, xatier commented on Source/Data/BPMFMappings.txt
> +麻芛 ㄇㄚˊ ㄧˋ
說文解字

> 《艸部》芛：艸之葟榮也。从艸尹聲。

https://ctext.org/dictionary.pl?if=gb&id=26674

2024-07-16 14:10 UTC, xatier commented
Rebase on top of master.

2024-07-17 04:58 UTC, tianjianjiang commented on Source/Data/BPMFMappings.txt
> +麻芛 ㄇㄚˊ ㄧˋ
總之要加上去的話我個人沒問題～

以下單純聊天：
「尹聲」在說文裡很有可能是聲調。不過說文在這方面不太精確。
不過 ctext 可以查到一些線索
https://ctext.org/dictionary.pl?if=gb&char=%E8%8A%9B
比如說「羊捶切」的話很有可能聽起來還是像 ㄨㄟˇ
https://suzukish.sakura.ne.jp/search/inkyo/index.php?targetXiaoyun=w30440

2024-07-17 04:59 UTC, tianjianjiang approved these changes

2024-07-28 10:40 UTC, merged